name: CI/CD HTML

on:
  push:
    branches: [ "principal" ]
  pull_request:
    branches: [ "principal" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Verificar arquivos HTML
        run: ls -la *.html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy concluido
        run: echo "Deploy realizado com sucesso!"
